CREATE DATABASE quiz;
CREATE USER 'quizmaster'@'localhost' IDENTIFIED BY 'qu!z_m150';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON quiz.* TO 'quizmaster'@'localhost';